
export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'
export const SET_GENRE = 'SET_GENRE'
export const SET_QUALITY = 'SET_QUALITY'
export const SET_RATING = 'SET_RATING'
export const SET_RELEASE_YEAR = 'SET_RELEASE_YEAR'
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'