
export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST'
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS'
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE'
export const GET_QUALITIES = 'GET_QUALITIES'